# Generated by Django 3.1.2 on 2020-10-28 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('icao', models.CharField(max_length=5)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Longitud')),
                ('altitude_feets', models.IntegerField()),
                ('time_zone', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('zip_code', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Longitud')),
                ('time_zone', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cuota')),
                ('balance_close_month', models.CharField(max_length=10)),
                ('payment_message', models.TextField(blank=True, null=True)),
                ('cuit', models.CharField(blank=True, max_length=17, null=True)),
                ('category_IVA', models.CharField(blank=True, max_length=25, null=True)),
                ('name_logo', models.CharField(blank=True, max_length=25, null=True)),
                ('active', models.BooleanField(default=True)),
                ('season_date', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(max_length=20)),
                ('airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretary.airport')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretary.city')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=60)),
                ('document_type', models.CharField(blank=True, max_length=15, null=True)),
                ('document_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('birthday_place', models.CharField(blank=True, max_length=60, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=20, null=True)),
                ('job', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cuit', models.CharField(blank=True, max_length=17, null=True)),
                ('categoryIVA', models.CharField(blank=True, max_length=25, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretary.city', verbose_name='Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(blank=True, max_length=10, null=True)),
                ('aircraft_license_type', models.CharField(blank=True, max_length=15, null=True)),
                ('aircraft_license_number', models.CharField(blank=True, max_length=15, null=True)),
                ('instructor_aircraft_license_number', models.CharField(blank=True, max_length=15, null=True)),
                ('glider_license_type', models.CharField(blank=True, max_length=15, null=True)),
                ('glider_license_number', models.CharField(blank=True, max_length=15, null=True)),
                ('instructor_glider_license_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_VFR', models.BooleanField(blank=True, default=True, null=True)),
                ('is_IFR', models.BooleanField(blank=True, default=False, null=True)),
                ('night_habilitation', models.BooleanField(blank=True, default=False, null=True)),
                ('is_single_engine', models.BooleanField(blank=True, default=True, null=True)),
                ('is_multi_engine', models.BooleanField(blank=True, default=False, null=True)),
                ('is_tug', models.BooleanField(blank=True, default=False, null=True)),
                ('is_turboprop', models.BooleanField(blank=True, default=False, null=True)),
                ('psychophysical_until', models.DateField(blank=True, null=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='secretary.person')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretary.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretary.province'),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('date_admission', models.DateField(blank=True, null=True)),
                ('act_number', models.IntegerField(blank=True, null=True)),
                ('presenter_1', models.CharField(blank=True, max_length=10, null=True)),
                ('presenter_2', models.CharField(blank=True, max_length=10, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretary.club')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretary.person')),
                ('pilot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretary.pilot')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretary.partnertype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('act_number', models.IntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=25, null=True)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='secretary.partner')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretary.province'),
        ),
        migrations.CreateModel(
            name='ActivePilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretary.club')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretary.pilot')),
            ],
        ),
    ]
