# Generated by Django 3.1.2 on 2020-12-22 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=60)),
                ('document_type', models.CharField(blank=True, max_length=15, null=True)),
                ('document_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('birthday_place', models.CharField(blank=True, max_length=60, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=20, null=True)),
                ('job', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cuit', models.CharField(blank=True, max_length=17, null=True)),
                ('categoryIVA', models.CharField(blank=True, max_length=25, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.city', verbose_name='Ciudad')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.province')),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(blank=True, max_length=10, null=True)),
                ('aircraft_license_type', models.CharField(blank=True, max_length=15, null=True)),
                ('aircraft_license_number', models.CharField(blank=True, max_length=15, null=True)),
                ('instructor_aircraft_license_number', models.CharField(blank=True, max_length=15, null=True)),
                ('glider_license_type', models.CharField(blank=True, max_length=15, null=True)),
                ('glider_license_number', models.CharField(blank=True, max_length=15, null=True)),
                ('instructor_glider_license_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_VFR', models.BooleanField(blank=True, default=True, null=True)),
                ('is_IFR', models.BooleanField(blank=True, default=False, null=True)),
                ('night_habilitation', models.BooleanField(blank=True, default=False, null=True)),
                ('is_single_engine', models.BooleanField(blank=True, default=True, null=True)),
                ('is_multi_engine', models.BooleanField(blank=True, default=False, null=True)),
                ('is_tug', models.BooleanField(blank=True, default=False, null=True)),
                ('is_turboprop', models.BooleanField(blank=True, default=False, null=True)),
                ('psychophysical_until', models.DateField(blank=True, null=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='secretary.person')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretary.person')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('date_admission', models.DateField(blank=True, null=True)),
                ('act_number', models.IntegerField(blank=True, null=True)),
                ('presenter_1', models.CharField(blank=True, max_length=10, null=True)),
                ('presenter_2', models.CharField(blank=True, max_length=10, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.club')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretary.person')),
                ('pilot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretary.pilot')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretary.partnertype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('act_number', models.IntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=25, null=True)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='secretary.partner')),
            ],
        ),
        migrations.CreateModel(
            name='ActivePilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.club')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretary.pilot')),
            ],
        ),
    ]
