# Generated by Django 3.1.2 on 2020-10-29 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201029_0957'),
        ('secretary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='province',
        ),
        migrations.RemoveField(
            model_name='club',
            name='airport',
        ),
        migrations.RemoveField(
            model_name='club',
            name='city',
        ),
        migrations.AlterField(
            model_name='activepilot',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.club'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.club'),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.city', verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='person',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.province'),
        ),
        migrations.DeleteModel(
            name='Airport',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
