# Generated by Django 3.1.2 on 2020-10-26 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('icao', models.CharField(max_length=5)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='longitude')),
                ('altitude_feets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('zip_code', models.CharField(max_length=10)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='fee')),
                ('balance_close_month', models.CharField(max_length=10)),
                ('payment_message', models.TextField()),
                ('cuit', models.CharField(max_length=17)),
                ('category_IVA', models.CharField(max_length=25)),
                ('name_logo', models.CharField(max_length=25)),
                ('active', models.BooleanField(default=True)),
                ('season_date', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=20)),
                ('airport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('document_type', models.CharField(max_length=15)),
                ('document_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('zip_code', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('birthday_place', models.CharField(max_length=60)),
                ('citizenship', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('cuit', models.CharField(max_length=17)),
                ('categoryIVA', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(max_length=10)),
                ('aircraft_license_type', models.CharField(max_length=15)),
                ('aircraft_license_number', models.CharField(max_length=15)),
                ('instructor_aircraft_license_number', models.CharField(max_length=15)),
                ('glider_license_type', models.CharField(max_length=15)),
                ('glider_license_number', models.CharField(max_length=15)),
                ('instructor_glider_license_number', models.CharField(max_length=15)),
                ('is_VFR', models.BooleanField(default=True)),
                ('is_IFR', models.BooleanField(default=False)),
                ('night_habilitation', models.BooleanField(default=False)),
                ('is_single_engine', models.BooleanField(default=True)),
                ('is_multi_engine', models.BooleanField(default=False)),
                ('is_tug', models.BooleanField(default=False)),
                ('is_turboprop', models.BooleanField(default=False)),
                ('psychophysical_until', models.DateField()),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.person')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.province'),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('pilot', models.IntegerField()),
                ('date_admission', models.DateField()),
                ('act_number', models.IntegerField()),
                ('type', models.CharField(max_length=25)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.club')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('act_number', models.IntegerField()),
                ('reason', models.CharField(max_length=25)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.partner')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.province'),
        ),
        migrations.CreateModel(
            name='ActivePilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.club')),
                ('pilot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.pilot')),
            ],
        ),
    ]
