# Generated by Django 3.1.2 on 2020-10-28 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='province',
        ),
        migrations.RemoveField(
            model_name='club',
            name='airport',
        ),
        migrations.RemoveField(
            model_name='club',
            name='city',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='club',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='group',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='person',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='pilot',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='type',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='user',
        ),
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='province',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='person',
        ),
        migrations.RemoveField(
            model_name='pilot',
            name='person',
        ),
        migrations.DeleteModel(
            name='ActivePilot',
        ),
        migrations.DeleteModel(
            name='Airport',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.DeleteModel(
            name='PartnerType',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.DeleteModel(
            name='Pilot',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
