# Generated by Django 3.1.2 on 2020-10-29 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_auto_20201028_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('icao', models.CharField(max_length=5)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Longitud')),
                ('altitude_feets', models.IntegerField()),
                ('time_zone', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('zip_code', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Longitud')),
                ('time_zone', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cuota')),
                ('balance_close_month', models.CharField(max_length=10)),
                ('payment_message', models.TextField(blank=True, null=True)),
                ('cuit', models.CharField(blank=True, max_length=17, null=True)),
                ('category_IVA', models.CharField(blank=True, max_length=25, null=True)),
                ('name_logo', models.CharField(blank=True, max_length=25, null=True)),
                ('active', models.BooleanField(default=True)),
                ('season_date', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(max_length=20)),
                ('airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.airport')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.province'),
        ),
    ]
