# Generated by Django 3.1.2 on 2020-10-26 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_airport_time_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='province',
        ),
        migrations.RemoveField(
            model_name='club',
            name='zip_code',
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('zip_code', models.CharField(max_length=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='longitude')),
                ('altitude_feets', models.IntegerField()),
                ('time_zone', models.IntegerField(blank=True, null=True)),
                ('province', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.province')),
            ],
        ),
        migrations.AlterField(
            model_name='club',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city'),
        ),
    ]
