# Generated by Django 3.1.2 on 2020-10-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_city_altitude_feets'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True, verbose_name='latitude'),
        ),
    ]
