# Generated by Django 3.1.2 on 2020-10-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201029_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubtype',
            old_name='type',
            new_name='name',
        ),
    ]
