# Generated by Django 3.1.2 on 2020-10-29 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201029_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryIVA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_IVA', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='clubtype',
            old_name='name',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='club',
            name='category_IVA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.categoryiva'),
        ),
    ]
