# Generated by Django 3.1.2 on 2020-10-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201029_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryiva',
            name='category_IVA',
            field=models.CharField(max_length=30),
        ),
    ]
