# Generated by Django 3.1.2 on 2020-10-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201026_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name_logo',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
