# Generated by Django 3.1.2 on 2020-10-27 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201026_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='partner',
            name='group',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='presenter_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='presenter_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.partnertype'),
        ),
    ]
