# Generated by Django 3.1.2 on 2020-10-27 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20201027_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.pilot'),
        ),
    ]
