# Generated by Django 3.1.2 on 2020-10-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20201027_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='number',
            field=models.IntegerField(verbose_name='Numero Socio'),
        ),
    ]
