# Generated by Django 3.1.2 on 2020-10-27 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20201027_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='club',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cuota'),
        ),
        migrations.AlterField(
            model_name='club',
            name='payment_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.city', verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Nombre'),
        ),
    ]
