# Generated by Django 3.1.2 on 2020-10-27 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20201027_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.club'),
        ),
    ]
