# Generated by Django 3.1.2 on 2020-10-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20201027_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='act_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='date_admission',
            field=models.DateField(blank=True, null=True),
        ),
    ]
