# Generated by Django 3.1.2 on 2020-10-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20201027_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='presenter_1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='presenter_2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
