# Generated by Django 3.1.2 on 2020-10-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20201027_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
